### 성적데이터 생성

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# DataFrame 형태로 성적 데이터 만들기
data = pd.DataFrame([[2,20], [4,40], [8,80], [9,90]],
             index=['인성', '준용', '승윤', '성진'],
             columns=['시간', '성적'])

In [8]:
data

시간  성적
인성   2  20
준용   4  40
승윤   8  80
성진   9  90

##### Linear Regression
- 수학 공식을 이용한 해석적 방법

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
# 모델 생성
linear_model = LinearRegression()

In [15]:
linear_model.fit(data[['시간']], data['성적']) # X_train, y_train

LinearRegression()

In [16]:
# 가중치(계수)
linear_model.coef_

array([10.])

In [17]:
# 편향(절편)
linear_model.intercept_

7.105427357601002e-15

In [18]:
# 예측
linear_model.predict([[7]])

array([70.])

In [20]:
linear_model.predict([[10]])

array([100.])